/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: e849cf45d3fda31ce81eb242a0b9b7c6)
interface __BaseEnv_Env {
	FIREBASE_PROJECT_NUMBER: "1081977371730";
	KOI_DAILY_REQUEST_LIMIT: "100";
	KOI_BETA_ENABLED: "false";
	KOI_ACTIVE_ACCOUNT_LIMIT: "50";
	KOI_APP_CHECK_REQUIRED: "false";
	KOI_PROVIDER_ENABLED: "true";
	KOI_USER: DurableObjectNamespace<import("./index").KoiUserObject>;
	KOI_GLOBAL: DurableObjectNamespace<import("./index").KoiGlobalObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "KoiUserObject" | "KoiGlobalObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FIREBASE_PROJECT_NUMBER" | "KOI_DAILY_REQUEST_LIMIT" | "KOI_BETA_ENABLED" | "KOI_ACTIVE_ACCOUNT_LIMIT" | "KOI_APP_CHECK_REQUIRED" | "KOI_PROVIDER_ENABLED">> {}
}
