/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: 9bb52060966e6761d001f4a5ed69a05c)
interface __BaseEnv_Env {
	FIREBASE_PROJECT_NUMBER: "1081977371730";
	KOI_BETA_ENABLED: "false";
	KOI_ACTIVE_ACCOUNT_LIMIT: "50";
	KOI_APP_CHECK_REQUIRED: "false";
	KOI_PROVIDER_ENABLED: "true";
	KOI_USAGE_MODE: "personal_unlimited";
	KOI_USER: DurableObjectNamespace /* KoiUserObject */;
	KOI_GLOBAL: DurableObjectNamespace /* KoiGlobalObject */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FIREBASE_PROJECT_NUMBER" | "KOI_BETA_ENABLED" | "KOI_ACTIVE_ACCOUNT_LIMIT" | "KOI_APP_CHECK_REQUIRED" | "KOI_PROVIDER_ENABLED" | "KOI_USAGE_MODE">> {}
}
