#!/usr/bin/env node
/**
 * Phase 22 audit fix P1-09 — dependency audit report generator.
 *
 * Runs `npm audit --omit=dev --json` and emits a markdown summary at
 * `docs/phase-22-dependency-audit.md`. CI can compare the file's
 * vulnerability counts against a baseline to gate releases.
 *
 * Usage:
 *   node scripts/audit-report.mjs
 *   npm run audit:report
 *
 * Output (docs/phase-22-dependency-audit.md) is committed so audit
 * history is visible alongside the code.
 */

import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = dirname(__dirname);
const OUT = join(ROOT, 'docs', 'phase-22-dependency-audit.md');
const PKG = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));

/**
 * Safely stringify npm-audit's `via` field without ever rendering
 * "[object Object]".
 *
 * npm-audit's `via` field can be:
 *   - an array of strings (advisory IDs / GHSA references)
 *   - an array of objects (`{ title, url, severity, ... }`)
 *   - a plain string (rare, but observed)
 *   - an object without `title` (rare, but observed)
 *   - null / undefined (when a vulnerability has no upstream advice)
 *
 * All shapes are mapped to a stable string. Unknown objects fall back to
 * `JSON.stringify` rather than the naive `String(...)` coercion that
 * would render the literal text "[object Object]".
 *
 * NOTE: This helper lives in the .mjs script because the .mjs cannot
 * import from a .ts file without a build step. The contract test
 * (tests/phase25P3StringifyViaField.test.ts) replicates this logic
 * inline and asserts every branch; pair any future change here with a
 * matching update to the inline copy in that test file.
 */
function stringifyViaField(via) {
  if (via == null) return 'unknown';
  if (typeof via === 'string') return via;
  if (Array.isArray(via)) {
    return via
      .map((x) => (typeof x === 'string' ? x : x && typeof x === 'object' && typeof x.title === 'string' ? x.title : null))
      .filter((s) => s !== null && s.length > 0)
      .join(', ') || 'unknown';
  }
  if (typeof via === 'object') {
    const obj = via;
    if (typeof obj.title === 'string') return obj.title;
    if (typeof obj.name === 'string') return obj.name;
    if (typeof obj.url === 'string') return obj.url;
    if (typeof obj.severity === 'string') return obj.severity;
    try {
      return JSON.stringify(via);
    } catch {
      return 'unknown';
    }
  }
  // numbers, booleans, bigints, symbols — never "[object Object]"
  if (typeof via === 'number' || typeof via === 'boolean' || typeof via === 'bigint') {
    return String(via);
  }
  return 'unknown';
}

function runAudit() {
  try {
    const out = execSync('npm audit --omit=dev --json', {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return JSON.parse(out);
  } catch (err) {
    // npm audit exits non-zero when vulnerabilities are found — capture the JSON from stdout.
    const stdout = err.stdout?.toString() || '';
    if (stdout) {
      try { return JSON.parse(stdout); } catch { /* fall through */ }
    }
    return { error: err.message };
  }
}

function summarise(report) {
  const meta = report.metadata?.vulnerabilities || {};
  // npm audit's report.metadata.dependencies is an object like
  // { prod: N, dev: M, optional: 0, peer: 0, peerOptional: 0, total: K }.
  // If we naively string-interpolate it, Markdown renders "[object Object]".
  // Sum the per-bucket counts to get a single integer.
  const depMeta = report.metadata?.dependencies;
  let depCount = 0;
  if (typeof depMeta === 'number') {
    depCount = depMeta;
  } else if (depMeta && typeof depMeta === 'object') {
    depCount = Object.values(depMeta).reduce(
      (sum, n) => sum + (typeof n === 'number' ? n : 0),
      0,
    );
  }
  return {
    total: meta.total ?? 0,
    info: meta.info ?? 0,
    low: meta.low ?? 0,
    moderate: meta.moderate ?? 0,
    high: meta.high ?? 0,
    critical: meta.critical ?? 0,
    dependencies: depCount,
  };
}

function topAdvisories(report, n = 10) {
  const all = Object.entries(report.vulnerabilities || {});
  return all
    .map(([name, v]) => ({
      name,
      severity: v.severity,
      via: stringifyViaField(v.via),
      range: v.range,
    }))
    .sort((a, b) => {
      const order = { critical: 0, high: 1, moderate: 2, low: 3, info: 4 };
      return (order[a.severity] ?? 9) - (order[b.severity] ?? 9);
    })
    .slice(0, n);
}

const report = runAudit();
const stats = summarise(report);
const top = topAdvisories(report);
const date = new Date().toISOString().slice(0, 10);

const md = [
  `# Phase 22 — Dependency Audit (P1-09)`,
  ``,
  `Generated by \`scripts/audit-report.mjs\` on ${date}.`,
  ``,
  `## Summary`,
  ``,
  `| Severity | Count |`,
  `|---|---|`,
  `| Critical | ${stats.critical} |`,
  `| High | ${stats.high} |`,
  `| Moderate | ${stats.moderate} |`,
  `| Low | ${stats.low} |`,
  `| Info | ${stats.info} |`,
  `| **Total** | **${stats.total}** |`,
  ``,
  `Total dependencies scanned: ${stats.dependencies}.`,
  ``,
  `## Top advisories (severity-sorted, capped at 10)`,
  ``,
  top.length === 0
    ? `_No vulnerabilities reported._`
    : [
        `| Package | Severity | Advisory | Range |`,
        `|---|---|---|---|`,
        ...top.map(a => `| ${a.name} | ${a.severity} | ${a.via.replace(/\|/g, '\\|')} | ${a.range} |`),
      ].join('\n'),
  ``,
  `## Pinned versions`,
  ``,
  ...Object.entries(PKG.dependencies || {})
    .filter(([_, v]) => typeof v === 'string' && !v.startsWith('^') && !v.startsWith('~'))
    .map(([k, v]) => `- \`${k}\`: \`${v}\``),
  ``,
  `## Reproducing`,
  ``,
  '```',
  `npm install`,
  `npm run audit:deps     # raw npm audit output, fails on moderate+`,
  `npm run audit:report   # regenerate this markdown report`,
  '```',
  ``,
  `## Notes`,
  ``,
  `- This script runs \`npm audit --omit=dev --json\` and writes a markdown summary.`,
  `- CI should fail if \`stats.critical > 0\` or \`stats.high > 0\` (release blocker).`,
  `- For phase 23, every release candidate must regenerate this file and check it in.`,
].join('\n');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, md, 'utf8');
console.log(`Wrote ${OUT}`);
console.log(`Vulnerabilities: total=${stats.total} critical=${stats.critical} high=${stats.high} moderate=${stats.moderate}`);

// Exit non-zero on critical/high to fail release gating.
if (stats.critical > 0 || stats.high > 0) {
  console.error('Release gate: critical or high vulnerabilities present.');
  process.exit(1);
}